### PR TITLE
minner change style

### PR DESCRIPTION
**Pull request by mohitjoshi81**

### CODE REVIEW

**Comment by xprilion** [comment]
Bullshit.

**Review by singhayushh — COMMENTED** [review]
What are these changes!?? @mohitjoshi81 please explain

**Comment by mohitjoshi81** [comment]
Hello ayush sir
Sorry sir , currently i am student in second year , and  this lockdown i
learn html and css and javascript. So i little bit know about github so i
randomly select repositories and analysis how to work in web development
and how to support   open source. i open your repo and learn how its work
and see your style site learn .
Sorry sir aap ko meri wajh problem hui he to meko nahi pata tha ki aap ki
repo changes ho jay ge .
Agli bar se me dhayan rakhuga . Pura analysis ke badh hi change karuga .
Aagre aapko lage meri wajh se kuchh problem hui he to man me koi si bhi
gali bak dena or eek bar smile kar dena😄
Or thank you last tak padne ke liye
Thank you  ayush sir

**Comment by singhayushh** [comment]
@mohitjoshi81 
First of all, I'm a first year student so don't call me sir please! 
- This repository does not belong to me but an [organization](https://winterofcode.com/) 
- If you are learning something and aren't confident enough of your command over the languages/stack, you shouldn't start contributing directly to major projects as it might break their code😅
- And please don't talk so colloquially!

**Comment by mohitjoshi81** [comment]
Ok ayush .i see anubhav sir profile so i think you elder for me

**Pull request closed without merging**
